// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      D:\Unity Projects\_P.GRUSZCZYNSKI\TranslationPluginExample\GDATranslationEditorPlugin\Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public partial class GDEItemKeys
    {
        public static string LanguageVersions_Sam_0_Texts_Text_0 = "Sam_0_Texts_Text_0";
        public static string LanguageVersions_Sam_0_Button_Text_1 = "Sam_0_Button_Text_1";
        public static string LanguageVersions_Sam_0_Button_Text_2 = "Sam_0_Button_Text_2";
        public static string LanguageVersions_Sam_0_Texts_Text_3 = "Sam_0_Texts_Text_3";
        public static string LanguageVersions_Sam_0_Texts_Text_4 = "Sam_0_Texts_Text_4";
        public static string LanguageVersions_Sam_0_Texts_Text_5 = "Sam_0_Texts_Text_5";
        public static string LanguageVersions_Sam_0_Texts_Text_6 = "Sam_0_Texts_Text_6";
        public static string LanguageVersions_Sam_0_Texts_Text_7 = "Sam_0_Texts_Text_7";
        public static string LanguageVersions_Sam_0_Texts_Text_8 = "Sam_0_Texts_Text_8";
        public static string LanguageVersions_Sam_0_Button_Text_9 = "Sam_0_Button_Text_9";
        public static string LanguageVersions_Sam_0_Button_Text_10 = "Sam_0_Button_Text_10";
        public static string LanguageVersions_Sam_0_Texts_Text_11 = "Sam_0_Texts_Text_11";
    }
}
